#!/bin/bash

# Extract and format data using jq, awk, and sed
name=$(jq -r '.name' data.json | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
formatted_height=$(jq -r '.height / 10' data.json | sed 's/$//') 
formatted_weight=$(jq -r '.weight / 10' data.json | sed 's/$//') 
type=$(jq -r '.types[0].type.name' data.json | awk '{print toupper(substr($0,1,1)) substr($0,2)}' | sed 's/$//')

# Print output in the exact required format
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."